#!/usr/bin/env bash
bsub < "submit_cpu_singular_ntn/lmpo2_typei_adult.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_appliances.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_bank.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_breast.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_car_evaluation.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_mushrooms.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_obesity.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_popularity.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_seoulBike.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_student_dropout.sh"
bsub < "submit_cpu_singular_ntn/lmpo2_typei_student_perf.sh"
bsub < "submit_cpu_singular_ntn/mmpo2_popularity.sh"
bsub < "submit_cpu_singular_ntn/mmpo2_typei_popularity.sh"
