#!/bin/bash
# Submit all missing NTN jobs

cd "$(dirname "$0")"

bsub < cpda/car_evaluation.sh
bsub < cpda/mushrooms.sh
bsub < cpda/student_dropout.sh
bsub < lmpo2/adult.sh
bsub < lmpo2/bank.sh
bsub < lmpo2/car_evaluation.sh
bsub < lmpo2/mushrooms.sh
bsub < lmpo2/student_dropout.sh
bsub < lmpo2_typei/adult.sh
bsub < lmpo2_typei/appliances.sh
bsub < lmpo2_typei/bank.sh
bsub < lmpo2_typei/breast.sh
bsub < lmpo2_typei/hearth.sh
bsub < lmpo2_typei/mushrooms.sh
bsub < lmpo2_typei/popularity.sh
bsub < lmpo2_typei/student_dropout.sh
bsub < lmpo2_typei/wine.sh
bsub < lmpo2_typei/winequalityc.sh
bsub < mmpo2/adult.sh
bsub < mmpo2/bank.sh
bsub < mmpo2/breast.sh
bsub < mmpo2/car_evaluation.sh
bsub < mmpo2/mushrooms.sh
bsub < mmpo2/popularity.sh
bsub < mmpo2/student_dropout.sh
bsub < mmpo2_typei/adult.sh
bsub < mmpo2_typei/bank.sh
bsub < mmpo2_typei/breast.sh
bsub < mmpo2_typei/car_evaluation.sh
bsub < mmpo2_typei/mushrooms.sh
bsub < mmpo2_typei/popularity.sh
bsub < mmpo2_typei/student_dropout.sh
bsub < mpo2/adult.sh
bsub < mpo2/bank.sh
bsub < mpo2/car_evaluation.sh
bsub < mpo2/mushrooms.sh
bsub < mpo2/student_dropout.sh
bsub < mpo2/winequalityc.sh
bsub < mpo2_typei/adult.sh
bsub < mpo2_typei/bank.sh
bsub < mpo2_typei/breast.sh
bsub < mpo2_typei/car_evaluation.sh
bsub < mpo2_typei/mushrooms.sh
bsub < mpo2_typei/student_dropout.sh
bsub < tnml_f/student_dropout.sh
bsub < tnml_p/mushrooms.sh
