#!/bin/sh
# Submit ALL GTN jobs to HPC
# 210 jobs

# Record submission timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

mkdir -p logs

bsub < hpc/large/job_gtn_mpo2_abalone.sh
bsub < hpc/large/job_gtn_lmpo2_abalone.sh
bsub < hpc/large/job_gtn_mmpo2_abalone.sh
bsub < hpc/large/job_gtn_mpo2_typei_abalone.sh
bsub < hpc/large/job_gtn_lmpo2_typei_abalone.sh
bsub < hpc/large/job_gtn_mmpo2_typei_abalone.sh
bsub < hpc/large/job_gtn_tnml_p_abalone.sh
bsub < hpc/large/job_gtn_tnml_f_abalone.sh
bsub < hpc/large/job_gtn_cpda_abalone.sh
bsub < hpc/large/job_gtn_cpda_typei_abalone.sh
bsub < hpc/large/job_gtn_mpo2_adult.sh
bsub < hpc/large/job_gtn_lmpo2_adult.sh
bsub < hpc/large/job_gtn_mmpo2_adult.sh
bsub < hpc/large/job_gtn_mpo2_typei_adult.sh
bsub < hpc/large/job_gtn_lmpo2_typei_adult.sh
bsub < hpc/large/job_gtn_mmpo2_typei_adult.sh
bsub < hpc/large/job_gtn_tnml_p_adult.sh
bsub < hpc/large/job_gtn_tnml_f_adult.sh
bsub < hpc/large/job_gtn_cpda_adult.sh
bsub < hpc/large/job_gtn_cpda_typei_adult.sh
bsub < hpc/large/job_gtn_mpo2_ai4i.sh
bsub < hpc/large/job_gtn_lmpo2_ai4i.sh
bsub < hpc/large/job_gtn_mmpo2_ai4i.sh
bsub < hpc/large/job_gtn_mpo2_typei_ai4i.sh
bsub < hpc/large/job_gtn_lmpo2_typei_ai4i.sh
bsub < hpc/large/job_gtn_mmpo2_typei_ai4i.sh
bsub < hpc/large/job_gtn_tnml_p_ai4i.sh
bsub < hpc/large/job_gtn_tnml_f_ai4i.sh
bsub < hpc/large/job_gtn_cpda_ai4i.sh
bsub < hpc/large/job_gtn_cpda_typei_ai4i.sh
bsub < hpc/large/job_gtn_mpo2_appliances.sh
bsub < hpc/large/job_gtn_lmpo2_appliances.sh
bsub < hpc/large/job_gtn_mmpo2_appliances.sh
bsub < hpc/large/job_gtn_mpo2_typei_appliances.sh
bsub < hpc/large/job_gtn_lmpo2_typei_appliances.sh
bsub < hpc/large/job_gtn_mmpo2_typei_appliances.sh
bsub < hpc/large/job_gtn_tnml_p_appliances.sh
bsub < hpc/large/job_gtn_tnml_f_appliances.sh
bsub < hpc/large/job_gtn_cpda_appliances.sh
bsub < hpc/large/job_gtn_cpda_typei_appliances.sh
bsub < hpc/large/job_gtn_mpo2_bank.sh
bsub < hpc/large/job_gtn_lmpo2_bank.sh
bsub < hpc/large/job_gtn_mmpo2_bank.sh
bsub < hpc/large/job_gtn_mpo2_typei_bank.sh
bsub < hpc/large/job_gtn_lmpo2_typei_bank.sh
bsub < hpc/large/job_gtn_mmpo2_typei_bank.sh
bsub < hpc/large/job_gtn_tnml_p_bank.sh
bsub < hpc/large/job_gtn_tnml_f_bank.sh
bsub < hpc/large/job_gtn_cpda_bank.sh
bsub < hpc/large/job_gtn_cpda_typei_bank.sh
bsub < hpc/medium/job_gtn_mpo2_bike.sh
bsub < hpc/medium/job_gtn_lmpo2_bike.sh
bsub < hpc/medium/job_gtn_mmpo2_bike.sh
bsub < hpc/medium/job_gtn_mpo2_typei_bike.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_bike.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_bike.sh
bsub < hpc/medium/job_gtn_tnml_p_bike.sh
bsub < hpc/medium/job_gtn_tnml_f_bike.sh
bsub < hpc/medium/job_gtn_cpda_bike.sh
bsub < hpc/medium/job_gtn_cpda_typei_bike.sh
bsub < hpc/small/job_gtn_mpo2_breast.sh
bsub < hpc/small/job_gtn_lmpo2_breast.sh
bsub < hpc/small/job_gtn_mmpo2_breast.sh
bsub < hpc/small/job_gtn_mpo2_typei_breast.sh
bsub < hpc/small/job_gtn_lmpo2_typei_breast.sh
bsub < hpc/small/job_gtn_mmpo2_typei_breast.sh
bsub < hpc/small/job_gtn_tnml_p_breast.sh
bsub < hpc/small/job_gtn_tnml_f_breast.sh
bsub < hpc/small/job_gtn_cpda_breast.sh
bsub < hpc/small/job_gtn_cpda_typei_breast.sh
bsub < hpc/medium/job_gtn_mpo2_car_evaluation.sh
bsub < hpc/medium/job_gtn_lmpo2_car_evaluation.sh
bsub < hpc/medium/job_gtn_mmpo2_car_evaluation.sh
bsub < hpc/medium/job_gtn_mpo2_typei_car_evaluation.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_car_evaluation.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_car_evaluation.sh
bsub < hpc/medium/job_gtn_tnml_p_car_evaluation.sh
bsub < hpc/medium/job_gtn_tnml_f_car_evaluation.sh
bsub < hpc/medium/job_gtn_cpda_car_evaluation.sh
bsub < hpc/medium/job_gtn_cpda_typei_car_evaluation.sh
bsub < hpc/medium/job_gtn_mpo2_concrete.sh
bsub < hpc/medium/job_gtn_lmpo2_concrete.sh
bsub < hpc/medium/job_gtn_mmpo2_concrete.sh
bsub < hpc/medium/job_gtn_mpo2_typei_concrete.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_concrete.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_concrete.sh
bsub < hpc/medium/job_gtn_tnml_p_concrete.sh
bsub < hpc/medium/job_gtn_tnml_f_concrete.sh
bsub < hpc/medium/job_gtn_cpda_concrete.sh
bsub < hpc/medium/job_gtn_cpda_typei_concrete.sh
bsub < hpc/medium/job_gtn_mpo2_energy_efficiency.sh
bsub < hpc/medium/job_gtn_lmpo2_energy_efficiency.sh
bsub < hpc/medium/job_gtn_mmpo2_energy_efficiency.sh
bsub < hpc/medium/job_gtn_mpo2_typei_energy_efficiency.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_energy_efficiency.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_energy_efficiency.sh
bsub < hpc/medium/job_gtn_tnml_p_energy_efficiency.sh
bsub < hpc/medium/job_gtn_tnml_f_energy_efficiency.sh
bsub < hpc/medium/job_gtn_cpda_energy_efficiency.sh
bsub < hpc/medium/job_gtn_cpda_typei_energy_efficiency.sh
bsub < hpc/small/job_gtn_mpo2_hearth.sh
bsub < hpc/small/job_gtn_lmpo2_hearth.sh
bsub < hpc/small/job_gtn_mmpo2_hearth.sh
bsub < hpc/small/job_gtn_mpo2_typei_hearth.sh
bsub < hpc/small/job_gtn_lmpo2_typei_hearth.sh
bsub < hpc/small/job_gtn_mmpo2_typei_hearth.sh
bsub < hpc/small/job_gtn_tnml_p_hearth.sh
bsub < hpc/small/job_gtn_tnml_f_hearth.sh
bsub < hpc/small/job_gtn_cpda_hearth.sh
bsub < hpc/small/job_gtn_cpda_typei_hearth.sh
bsub < hpc/small/job_gtn_mpo2_iris.sh
bsub < hpc/small/job_gtn_lmpo2_iris.sh
bsub < hpc/small/job_gtn_mmpo2_iris.sh
bsub < hpc/small/job_gtn_mpo2_typei_iris.sh
bsub < hpc/small/job_gtn_lmpo2_typei_iris.sh
bsub < hpc/small/job_gtn_mmpo2_typei_iris.sh
bsub < hpc/small/job_gtn_tnml_p_iris.sh
bsub < hpc/small/job_gtn_tnml_f_iris.sh
bsub < hpc/small/job_gtn_cpda_iris.sh
bsub < hpc/small/job_gtn_cpda_typei_iris.sh
bsub < hpc/large/job_gtn_mpo2_mushrooms.sh
bsub < hpc/large/job_gtn_lmpo2_mushrooms.sh
bsub < hpc/large/job_gtn_mmpo2_mushrooms.sh
bsub < hpc/large/job_gtn_mpo2_typei_mushrooms.sh
bsub < hpc/large/job_gtn_lmpo2_typei_mushrooms.sh
bsub < hpc/large/job_gtn_mmpo2_typei_mushrooms.sh
bsub < hpc/large/job_gtn_tnml_p_mushrooms.sh
bsub < hpc/large/job_gtn_tnml_f_mushrooms.sh
bsub < hpc/large/job_gtn_cpda_mushrooms.sh
bsub < hpc/large/job_gtn_cpda_typei_mushrooms.sh
bsub < hpc/medium/job_gtn_mpo2_obesity.sh
bsub < hpc/medium/job_gtn_lmpo2_obesity.sh
bsub < hpc/medium/job_gtn_mmpo2_obesity.sh
bsub < hpc/medium/job_gtn_mpo2_typei_obesity.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_obesity.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_obesity.sh
bsub < hpc/medium/job_gtn_tnml_p_obesity.sh
bsub < hpc/medium/job_gtn_tnml_f_obesity.sh
bsub < hpc/medium/job_gtn_cpda_obesity.sh
bsub < hpc/medium/job_gtn_cpda_typei_obesity.sh
bsub < hpc/large/job_gtn_mpo2_popularity.sh
bsub < hpc/large/job_gtn_lmpo2_popularity.sh
bsub < hpc/large/job_gtn_mmpo2_popularity.sh
bsub < hpc/large/job_gtn_mpo2_typei_popularity.sh
bsub < hpc/large/job_gtn_lmpo2_typei_popularity.sh
bsub < hpc/large/job_gtn_mmpo2_typei_popularity.sh
bsub < hpc/large/job_gtn_tnml_p_popularity.sh
bsub < hpc/large/job_gtn_tnml_f_popularity.sh
bsub < hpc/large/job_gtn_cpda_popularity.sh
bsub < hpc/large/job_gtn_cpda_typei_popularity.sh
bsub < hpc/medium/job_gtn_mpo2_realstate.sh
bsub < hpc/medium/job_gtn_lmpo2_realstate.sh
bsub < hpc/medium/job_gtn_mmpo2_realstate.sh
bsub < hpc/medium/job_gtn_mpo2_typei_realstate.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_realstate.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_realstate.sh
bsub < hpc/medium/job_gtn_tnml_p_realstate.sh
bsub < hpc/medium/job_gtn_tnml_f_realstate.sh
bsub < hpc/medium/job_gtn_cpda_realstate.sh
bsub < hpc/medium/job_gtn_cpda_typei_realstate.sh
bsub < hpc/medium/job_gtn_mpo2_seoulBike.sh
bsub < hpc/medium/job_gtn_lmpo2_seoulBike.sh
bsub < hpc/medium/job_gtn_mmpo2_seoulBike.sh
bsub < hpc/medium/job_gtn_mpo2_typei_seoulBike.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_seoulBike.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_seoulBike.sh
bsub < hpc/medium/job_gtn_tnml_p_seoulBike.sh
bsub < hpc/medium/job_gtn_tnml_f_seoulBike.sh
bsub < hpc/medium/job_gtn_cpda_seoulBike.sh
bsub < hpc/medium/job_gtn_cpda_typei_seoulBike.sh
bsub < hpc/large/job_gtn_mpo2_student_dropout.sh
bsub < hpc/large/job_gtn_lmpo2_student_dropout.sh
bsub < hpc/large/job_gtn_mmpo2_student_dropout.sh
bsub < hpc/large/job_gtn_mpo2_typei_student_dropout.sh
bsub < hpc/large/job_gtn_lmpo2_typei_student_dropout.sh
bsub < hpc/large/job_gtn_mmpo2_typei_student_dropout.sh
bsub < hpc/large/job_gtn_tnml_p_student_dropout.sh
bsub < hpc/large/job_gtn_tnml_f_student_dropout.sh
bsub < hpc/large/job_gtn_cpda_student_dropout.sh
bsub < hpc/large/job_gtn_cpda_typei_student_dropout.sh
bsub < hpc/medium/job_gtn_mpo2_student_perf.sh
bsub < hpc/medium/job_gtn_lmpo2_student_perf.sh
bsub < hpc/medium/job_gtn_mmpo2_student_perf.sh
bsub < hpc/medium/job_gtn_mpo2_typei_student_perf.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_student_perf.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_student_perf.sh
bsub < hpc/medium/job_gtn_tnml_p_student_perf.sh
bsub < hpc/medium/job_gtn_tnml_f_student_perf.sh
bsub < hpc/medium/job_gtn_cpda_student_perf.sh
bsub < hpc/medium/job_gtn_cpda_typei_student_perf.sh
bsub < hpc/small/job_gtn_mpo2_wine.sh
bsub < hpc/small/job_gtn_lmpo2_wine.sh
bsub < hpc/small/job_gtn_mmpo2_wine.sh
bsub < hpc/small/job_gtn_mpo2_typei_wine.sh
bsub < hpc/small/job_gtn_lmpo2_typei_wine.sh
bsub < hpc/small/job_gtn_mmpo2_typei_wine.sh
bsub < hpc/small/job_gtn_tnml_p_wine.sh
bsub < hpc/small/job_gtn_tnml_f_wine.sh
bsub < hpc/small/job_gtn_cpda_wine.sh
bsub < hpc/small/job_gtn_cpda_typei_wine.sh
bsub < hpc/medium/job_gtn_mpo2_winequalityc.sh
bsub < hpc/medium/job_gtn_lmpo2_winequalityc.sh
bsub < hpc/medium/job_gtn_mmpo2_winequalityc.sh
bsub < hpc/medium/job_gtn_mpo2_typei_winequalityc.sh
bsub < hpc/medium/job_gtn_lmpo2_typei_winequalityc.sh
bsub < hpc/medium/job_gtn_mmpo2_typei_winequalityc.sh
bsub < hpc/medium/job_gtn_tnml_p_winequalityc.sh
bsub < hpc/medium/job_gtn_tnml_f_winequalityc.sh
bsub < hpc/medium/job_gtn_cpda_winequalityc.sh
bsub < hpc/medium/job_gtn_cpda_typei_winequalityc.sh

# Mark as submitted
echo "Submitted at $TIMESTAMP" > submitted_submit_all_hpc_$TIMESTAMP
echo "Submitted 210 jobs at $(date)"
