# @package _global_
# Settings for large datasets

dataset:
  size: large
  batch_size: 128

slurm:
  partition: titans
  time: "24:00:00"
  mem: "2gb"
  gpu_arch: Ampere
  cpus: 1
  gpu: 1

hpc:
  queue: gpuv100
  time: "24:00"
  mem: "500MB"
  cpus: 4
  gpu: 1
