# @package _global_
# Settings for small datasets

dataset:
  size: small
  batch_size: 256

slurm:
  partition: titans
  time: "12:00:00"
  mem: "2gb"
  gpu_arch: Ampere
  cpus: 1
  gpu: 1

hpc:
  queue: gpuv100
  time: "12:00"
  mem: "500MB"
  cpus: 4
  gpu: 1
